/** @file
 * Copyright (c) 2022-2025, 2026, Arm Limited or its affiliates. All rights reserved.
 * SPDX-License-Identifier : Apache-2.0

 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **/


/** This file is common to all test cases and Val layer of the Suite */


#ifndef __RME_ACS_COMMON_H__
#define __RME_ACS_COMMON_H__

#include <stdbool.h>
#include "val_memory.h"

#define DA_MODULE        "da"
#define DPT_MODULE       "dpt"
#define GIC_MODULE       "gic"
#define LEGACY_MODULE    "legacy"
#define MEC_MODULE       "mec"
#define RME_MODULE       "rme"
#define SMMU_MODULE      "smmu"
#define CXL_MODULE       "cxl"
#define CDA_MODULE       "cda"
#define TDISP_MODULE     "tdisp"


bool acs_list_contains(const char8_t **list, uint32_t count, const char8_t *value);
bool acs_is_module_enabled(const char8_t *module_id);

#define CPU_NUM_BIT  32
#define CPU_NUM_MASK 0xFFFFFFFF

#define LEVEL_BIT    24
#define LEVEL_MASK  0xF

#define IS_TEST_END(status)        (val_memory_compare("END", status, sizeof("END")) == 0)
#define IS_RESULT_PENDING(status)  (val_memory_compare("PENDING", status, sizeof("PENDING")) == 0)
#define IS_TEST_PASS(status)       (val_memory_compare("PASS", status, sizeof("PASS")) == 0)
#define IS_TEST_FAIL(status)       (val_memory_compare("FAIL", status, sizeof("FAIL")) == 0)
#define IS_TEST_SKIP(status)       (val_memory_compare("SKIP", status, sizeof("SKIP")) == 0)
#define IS_TEST_FAIL_SKIP(status)  (IS_TEST_FAIL(status) || IS_TEST_SKIP(status))

uint8_t
val_mmio_read8(addr_t addr);

uint16_t
val_mmio_read16(addr_t addr);

uint32_t
val_mmio_read(addr_t addr);

uint64_t
val_mmio_read64(addr_t addr);

void
val_mmio_write8(addr_t addr, uint8_t data);

void
val_mmio_write16(addr_t addr, uint16_t data);

void
val_mmio_write(addr_t addr, uint32_t data);

void
val_mmio_write64(addr_t addr, uint64_t data);

uint32_t
val_check_skip_module(char8_t *module_id);

uint32_t
val_initialize_test(char8_t *testname, char8_t *desc, uint32_t num_pe, char8_t *ruleid);

uint32_t
val_check_for_error(uint32_t num_pe);

void
val_run_test_payload(uint32_t num_pe, void (*payload)(void), uint64_t test_input);


void
val_data_cache_ops_by_va(addr_t addr, uint32_t type);

typedef enum {
    RME_MODULE_ID,
    GIC_MODULE_ID,
    SMMU_MODULE_ID,
    DA_MODULE_ID,
    DPT_MODULE_ID,
    MEC_MODULE_ID,
    LEGACY_MODULE_ID,
    CXL_MODULE_ID,
    CDA_MODULE_ID,
    TDISP_MODULE_ID,
    MODULE_SENTINEL,
} MODULE_ID_e;

/* Function signature for every test entry point */
typedef uint32_t (*test_entry_fn)(uint32_t num_pe);

/* Enumerations of test entry functions per module (found under test_pool/) */
typedef enum {
    CDA_MODULE_START = -1,
    CDA_ENTRY_CDA_RJZQCP_RESET_TRANSITION_ENTRY,
    CDA_ENTRY_CDA_RKRCWK_HOST_SIDE_GPC_ENTRY,
    CDA_MODULE_END,
} CDA_TEST_ENTRY_e;

typedef enum {
    CXL_MODULE_START = -1,
    CXL_ENTRY_CXL_RJSDVG_LITTLE_ENDIAN_ENTRY,
    CXL_ENTRY_CXL_RPLYKV_RDFWKW_RME_CDA_DVSEC_ENTRY,
    CXL_ENTRY_CXL_RGVRQC_HOST_PORT_COVERAGE_ENTRY,
    CXL_ENTRY_CXL_HOST_PORT_RMSD_WRITE_PROTECT_ENTRY,
    CXL_ENTRY_CXL_RWPGJB_RMSD_WRITE_PROTECT_PROPERTY_ENTRY,
    CXL_ENTRY_CXL_RPHCGC_RMSD_FULL_PROTECT_ENTRY,
    CXL_ENTRY_CXL_RLQMCY_TYPE3_HOST_MPE_ENTRY,
    CXL_ENTRY_CXL_RDHWNR_LINK_STREAM_LOCK_ENTRY,
    CXL_ENTRY_CXL_RWYVCQ_LINK_UNLOCK_REJECT_ENTRY,
    CXL_ENTRY_CXL_RXQHNG_RID_RANGE_REJECT_ENTRY,
    CXL_ENTRY_CXL_RKJYPB_CACHE_DISABLE_ENTRY,
    CXL_ENTRY_CXL_RPHWMM_RME_CDA_TSP_ENTRY,
    CXL_ENTRY_CXL_RJXPZP_PAS_CKID_MAPPING_ENTRY,
    CXL_ENTRY_CXL_RPLCMC_TYPE3_TARGET_CKID_ENTRY,
    CXL_ENTRY_CXL_RCNSLJ_TYPE3_NO_TSP_ENTRY,
    CXL_ENTRY_CXL_RHCQWS_HOST_SIDE_MPE_ENTRY,
    CXL_ENTRY_CXL_RPTGGP_CMO_TO_CXL_MEM_ENTRY,
    CXL_ENTRY_CXL_RHHMVM_BISNP_PAS_NONSECURE_ENTRY,
    CXL_ENTRY_CXL_RBYTYV_ROOT_PORT_PAS_BEHAVIOR_ENTRY,
    CXL_ENTRY_CXL_RNYCLL_TDISP_DISABLE_REJECT_ENTRY,
    CXL_ENTRY_CXL_RGTVGZ_TDISP_ENABLE_LINK_GATE_ENTRY,
    CXL_ENTRY_CXL_RHMXTF_HOST_HDM_DECODER_ENTRY,
    CXL_ENTRY_CXL_RGBGQX_CTC_LINK_IDE_ENTRY,
    CXL_ENTRY_CXL_RXWJNN_TYPE3_LINK_IDE_ENTRY,
    CXL_ENTRY_CXL_RFDVZC_TDISP_DISABLE_ENTRY,
    CXL_MODULE_END,
} CXL_TEST_ENTRY_e;

typedef enum {
    DA_MODULE_START = -1,
    DA_ENTRY_DA_DVSEC_REGISTER_CONFIG_ENTRY,
    DA_ENTRY_DA_SMMU_IMPLEMENTATION_ENTRY,
    DA_ENTRY_DA_TEE_IO_CAPABILITY_ENTRY,
    DA_ENTRY_DA_ROOTPORT_IDE_FEATURES_ENTRY,
    DA_ENTRY_DA_ATTRIBUTE_RMEDA_CTL_REGISTERS_ENTRY,
    DA_ENTRY_DA_P2P_BTW_2_TDISP_DEVICES_ENTRY,
    DA_ENTRY_DA_OUTGOING_REQUEST_WITH_IDE_TBIT_ENTRY,
    DA_ENTRY_DA_INCOMING_REQUEST_IDE_SEC_LOCKED_ENTRY,
    DA_ENTRY_DA_CTL_REGS_RMSD_WRITE_PROTECT_PROPERTY_ENTRY,
    DA_ENTRY_DA_IDE_STATE_ROOTPORT_ERROR_ENTRY,
    DA_ENTRY_DA_IDE_STATE_TDISP_DISABLE_ENTRY,
    DA_ENTRY_DA_SELECTIVE_IDE_REGISTER_PROPERTY_ENTRY,
    DA_ENTRY_DA_ROOTPORT_TDISP_DISABLED_ENTRY,
    DA_ENTRY_DA_AUTONOMOUS_ROOTPORT_REQUEST_NS_PAS_ENTRY,
    DA_ENTRY_DA_INCOMING_REQUEST_IDE_NON_SEC_UNLOCKED_ENTRY,
    DA_ENTRY_DA_OUTGOING_REALM_RQST_IDE_TBIT_1_ENTRY,
    DA_ENTRY_DA_IDE_TBIT_0_FOR_ROOT_REQUEST_ENTRY,
    DA_ENTRY_DA_RMSD_WRITE_DETECT_PROPERTY_ENTRY,
    DA_ENTRY_DA_ROOTPORT_WRITE_PROTECT_FULL_PROTECT_PROPERTY_ENTRY,
    DA_ENTRY_DA_INTERCONNECT_REGS_RMSD_PROTECTED_ENTRY,
    DA_MODULE_END,
} DA_TEST_ENTRY_e;

typedef enum {
    DPT_MODULE_START = -1,
    DPT_ENTRY_DPT_SYSTEM_RESOURCE_VALID_WITHOUT_DPTI_ENTRY,
    DPT_ENTRY_DPT_SYSTEM_RESOURCE_VALID_WITH_DPTI_ENTRY,
    DPT_ENTRY_DPT_SYSTEM_RESOURCE_INVALID_ENTRY,
    DPT_ENTRY_DPT_P2P_DIFFERENT_ROOTPORT_VALID_ENTRY,
    DPT_ENTRY_DPT_P2P_DIFFERENT_ROOTPORT_INVALID_ENTRY,
    DPT_ENTRY_DPT_P2P_SAME_ROOTPORT_VALID_ENTRY,
    DPT_ENTRY_DPT_P2P_SAME_ROOTPORT_INVALID_ENTRY,
    DPT_MODULE_END,
} DPT_TEST_ENTRY_e;

typedef enum {
    GIC_MODULE_START = -1,
    GIC_ENTRY_GIC_ITS_SUBJECTED_TO_GPC_CHECK_ENTRY,
    GIC_MODULE_END,
} GIC_TEST_ENTRY_e;

typedef enum {
    LEGACY_MODULE_START = -1,
    LEGACY_ENTRY_LEGACY_TZ_SUPPORT_CHECK_ENTRY,
    LEGACY_ENTRY_LEGACY_TZ_EN_DRIVES_ROOT_TO_SECURE_ENTRY,
    LEGACY_ENTRY_LEGACY_TZ_ENABLE_BEFORE_RESETV_ENTRY,
    LEGACY_ENTRY_LEGACY_TZ_ENABLE_AFTER_RESET_ENTRY,
    LEGACY_MODULE_END,
} LEGACY_TEST_ENTRY_e;

typedef enum {
    MEC_MODULE_START = -1,
    MEC_ENTRY_MEC_SUPPORT_MECID_AND_MECID_WIDTH_ENTRY,
    MEC_ENTRY_MEC_MECID_ASSOSIATION_AND_ENCRYPTION_ENTRY,
    MEC_ENTRY_MEC_EFFECT_OF_POPA_CMO_ENTRY,
    MEC_ENTRY_MEC_CMO_USES_CORRECT_MECID_ENTRY,
    MEC_MODULE_END,
} MEC_TEST_ENTRY_e;

typedef enum {
    RME_MODULE_START = -1,
    RME_ENTRY_RME_SUPPORT_IN_PE_ENTRY,
    RME_ENTRY_RME_GPRS_SCRUBBED_AFTER_RESET_ENTRY,
    RME_ENTRY_RME_ALL_PE_HAS_FEAT_RNG_OR_RNG_TRAP_ENTRY,
    RME_ENTRY_RME_GPC_FOR_SYSTEM_RESOURCE_ENTRY,
    RME_ENTRY_RME_COHERENT_INTERCONNECT_SUPPORTS_CMO_POPA_ENTRY,
    RME_ENTRY_RME_RESOURCES_ALIGNED_TO_GRANULARITY_ENTRY,
    RME_ENTRY_RME_RESOURCES_ARE_NOT_PHYSICALLY_ALIASED_ENTRY,
    RME_ENTRY_RME_PE_DO_NOT_HAVE_ARCH_DIFF_ENTRY,
    RME_ENTRY_RME_MTE_REGION_IN_ROOT_PAS_ENTRY,
    RME_ENTRY_RME_ENCRYPTION_FOR_ALL_PAS_EXCEPT_NS_ENTRY,
    RME_ENTRY_RME_PAS_FILTER_FUNCTIONALITY_ENTRY,
    RME_ENTRY_RME_REALM_SMEM_BEHAVIOUR_AFTER_RESET_ENTRY,
    RME_ENTRY_RME_PCIE_DEVICES_SUPPORT_GPC_ENTRY,
    RME_ENTRY_RME_DATA_ENCRYPTION_BEYOND_POPA_ENTRY,
    RME_ENTRY_RME_DATA_ENCRYPTION_WITH_DIFFERENT_TWEAK_ENTRY,
    RME_ENTRY_RME_MSD_SMEM_IN_ROOT_PAS_ENTRY,
    RME_ENTRY_RME_REALM_SMEM_IN_REALM_PAS_ENTRY,
    RME_ENTRY_RME_SNOOP_FILTER_CONSIDERS_PAS_ENTRY,
    RME_ENTRY_RME_CMO_POPA_FOR_CACHEABILITY_SHAREABILITY_ENTRY,
    RME_ENTRY_RME_MEMORY_ASSOCIATED_WITH_PAS_TILL_POPA_ENTRY,
    RME_ENTRY_RME_INTERCONNECT_SUPPORTS_TLBI_PA_ENTRY,
    RME_ENTRY_RME_NS_ENCRYPTION_IS_IMMUTABLE_ENTRY,
    RME_ENTRY_RME_PE_CONTEXT_AFTER_EXIT_WFI_ENTRY,
    RME_ENTRY_RME_PE_CONTEXT_AFTER_PE_SUSPEND_ENTRY,
    RME_ENTRY_RME_MSD_SAVE_RESTORE_MEM_IN_ROOT_PAS_ENTRY,
    RME_ENTRY_RME_RNVS_IN_ROOT_PAS_ENTRY,
    RME_ENTRY_RME_ROOT_WDOG_FROM_ROOT_PAS_ENTRY,
    RME_ENTRY_RME_ROOT_WDOG_FAILS_IN_NON_ROOT_STATE_ENTRY,
    RME_ENTRY_RME_PAS_FILTER_IN_INACTIVE_MODE_ENTRY,
    RME_ENTRY_RME_SMMU_BLOCKS_REQUEST_AT_REGISTERS_RESET_ENTRY,
    RME_ENTRY_RME_SYSTEM_RESET_PROPAGATION_TO_ALL_PE_ENTRY,
    RME_ENTRY_RME_MSD_SMEM_IN_ROOT_AFTER_RESET_ENTRY,
    RME_MODULE_END,
} RME_TEST_ENTRY_e;

typedef enum {
    SMMU_MODULE_START = -1,
    SMMU_ENTRY_SMMU_IMPLEMENTS_RME_ENTRY,
    SMMU_ENTRY_SMMU_RESPONDS_TO_GPT_TLB_ENTRY,
    SMMU_MODULE_END,
} SMMU_TEST_ENTRY_e;

typedef enum {
    TDISP_MODULE_START = -1,
    TDISP_ENTRY_TDISP_RFPYMV_VDM_RESPONSE_CHECK_ENTRY,
    TDISP_ENTRY_TDISP_RPXLFY_GET_VERSION_REQ_ENTRY,
    TDISP_ENTRY_TDISP_RWFWLF_GET_VERSION_RESP_FORMAT_ENTRY,
    TDISP_ENTRY_TDISP_RGRPDP_GET_DEV_PROP_REQ_ENTRY,
    TDISP_ENTRY_TDISP_RGHDCB_GET_DEV_PROP_RESP_FORMAT_ENTRY,
    TDISP_ENTRY_TDISP_RWFPXR_TDISP_ERROR_ALLOWED_ENTRY,
    TDISP_ENTRY_TDISP_RXDKDT_SET_INTERFACE_REQ_SEMANTICS_ENTRY,
    TDISP_ENTRY_TDISP_RFMHST_SET_INTERFACE_RESP_FORMAT_ENTRY,
    TDISP_MODULE_END,
} TDISP_TEST_ENTRY_e;

#define MAX_TEST_ENTRY (CDA_MODULE_END + CXL_MODULE_END + DA_MODULE_END + \
                        DPT_MODULE_END + GIC_MODULE_END + \
                        LEGACY_MODULE_END + MEC_MODULE_END + RME_MODULE_END + \
                        SMMU_MODULE_END + TDISP_MODULE_END)

typedef struct {
    test_entry_fn entry_fn;
    char8_t      *test_text;
} MODULE_TEST_ENTRY_s;

/* Aggregate test dispatch table sized to the sum of per-module entries */
typedef struct {
    MODULE_ID_e          module_id;
    MODULE_TEST_ENTRY_s  entry[MAX_TEST_ENTRY];
} MODULE_TEST_DISPATCHER_s;

extern MODULE_TEST_DISPATCHER_s g_module_test_table[MODULE_SENTINEL];
extern uint32_t *g_execute_tests;
extern uint32_t g_num_tests;

/* Selection helper: returns non-zero if the test should be executed */
int
val_test_is_selected(char8_t *test_text);

/* Execute a module's test entries using dispatcher table */
uint32_t
val_execute_module_tests(MODULE_ID_e module_id,
                         int start_enum,
                         int end_enum,
                         uint32_t num_pe,
                         uint32_t status);
#endif
